env: dev
http_server:
  address: ":3000"
mongodb:
  uri: "mongodb+srv://mango_admin:<db_password>@cluster0.8f8ra92.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  mongo_user: mango_admin
  mongo_pass: Mango@007

